const actionTypes = {
    GET_REDDIT_POST: 'GET_REDDIT_POST',
    GET_REDDIT_POST_SUCCESS: 'GET_REDDIT_POST_SUCCESS',
    GET_REDDIT_POST_FAILED: 'GET_REDDIT_POST_FAILED',
    GET_NAVIGATION_MENU : 'GET_NAVIGATION_MENU',
    GET_NAVIGATION_MENU_SUCCESS: 'GET_NAVIGATION_MENU_SUCCESS',
    GET_NAVIGATION_MENU_FAILED: 'GET_NAVIGATION_MENU_FAILED'
};

export default actionTypes;
